# requiring the environment of Ruby 2.3.x
image: ruby:4.0

# Set to production
variables:
  JEKYLL_ENV: production

# add cache to 'vendor' for speeding up builds
cache:
  paths: 
    - vendor/

before_script:
  - bundle config set path 'vendor'
  - bundle install

# add a job called 'test'
test:
  stage: test
  script:
    - bundle exec jekyll build --verbose -d test/
  artifacts:
    paths:
      - test # generating site folder to be browsed or download
  except:
    - main # the 'test' job will affect all branches expect 'main'

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - bundle exec jekyll build  --verbose -d public/
#    - mkdir -p public/.well-known/acme-challenge/ # Add Let's Encrypt support
#    - cp le/*  public/.well-known/acme-challenge/ # Copy Let's Encrypt support
  artifacts:
    paths:
      - public
  only:
    - main # this job will affect only the 'main' branch
