source 'https://rubygems.org'

gem 'csv'
gem 'jekyll', '~> 4.3'
gem 'jekyll-feed', '~> 0.17'
gem 'jekyll-paginate', '~> 1.1'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag', '~> 2.8'
gem 'jekyll-sass-converter', '~> 3.0'
gem 'kramdown-parser-gfm', '~> 1.1'
gem 'wdm', '>= 0.1.0'
